version: "3.8"

services:
  api:
    build: .
    container_name: mern_api
    restart: unless-stopped
    env_file: ./envs/api.env
    ports:
      - "3000:3000"           # internal mapping; Caddy will proxy to port 3000
    depends_on:
      - mongo
    networks:
      - mern_net
    volumes:
      - ./logs/api:/usr/src/app/logs
      - ./uploads:/usr/src/app/uploads

  mongo:
    image: mongo:6.0
    container_name: mern_mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - mongo-data:/data/db
    networks:
      - mern_net

  mongo-express:       # optional admin UI, remove if you don't want it
    image: mongo-express
    container_name: mongo_express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - "8081:8081"
    networks:
      - mern_net

volumes:
  mongo-data:

networks:
  mern_net:
    driver: bridge
